sudo: required

services:
  - docker

branches:
  only:
    - master
    - travis

before_script:
  # this install.sh script requires sudo
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh

script:
  - export HEROKU_API_KEY=$HEROKU_TOKEN
  - python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
  - ./start_env.sh deploy_pipeline

