
version: '3'
services:
  flaskapp:
    build: 
      context: .
      dockerfile: ./Dockerfile_do
    # env_file:
    #   - ./containers/env.txt
    # volumes:
    #  - .:/opt/services/flaskapp/src
    # networks:
    #   - web_nw
    # ports:
    #   - 8080:5000
  # nginx:
  #   image: "nginx:1.16.0"
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
  #   networks:
  #     - web_nw
  #   depends_on: 
  #     - flaskapp
# networks:
#   - web_nw
    # driver: bridge
  # db_nw:
  #   driver: bridge
# volumes:
#   dbdata: