# version: '3.7'
# services:
#   flaskapp:
#     build:
#       context: .
#       dockerfile: ./Dockerfile_do
#     command: gunicorn --bind 0.0.0.0:5000 wsgi
#     ports:
#       - "8080:5000"
#     # env_file:
#     #   - ./containers/env.txt
#     # volumes:
#     #  - .:/opt/services/flaskapp/src
#     networks:
#       web_nw:
#               aliases:
#                       - webapp
#     # ports:
#     #   - 8080:5000
#   nginx:
#     image: "nginx:1.16.0"
#     ports:
#       - 80:5000
#     volumes:
#       - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
#     networks:
#       - web_nw
#     depends_on:
#       - flaskapp
# networks:
#   web_nw:
#     driver: bridge
#   # db_nw:
#   #   driver: bridge
# # volumes:
# #   dbdata:

services:
  flask:
    build: 
      context: .
      dockerfile: ./Dockerfile_do
    volumes:
      - data:/opt/app/
    expose:
      - "5000"
    networks:
      - web

  nginx:
    image: nginx:alpine
    volumes:
      - data:/app:ro
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - web

networks:
  web:

volumes:
  data: